backend:
  name: github
  repo: giopunt/DAAM

media_folder: static/assets
public_folder: /assets

collections:
  - name: gallery
    label: Gallery
    folder: galleries
    create: true
    slug: "{{slug}}"
    fields:
      - { label: draft, name: Draft, widget: boolean, default: true }
      - { name: name, label: Name, widget: string }
      - { name: website, label: Website, widget: string, required: false }
      - { name: logo, label: Logo, widget: image, required: false }
      - { name: address, label: Address, widget: markdown }
      - { name: contacts, label: Contacts, widget: markdown }
      - { name: description, label: Description, widget: markdown }
      - { name: hero, label: Hero, widget: image, required: false }
      - { name: path, label: Path }
  - name: event
    label: Event
    folder: events
    create: true
    slug: "{{slug}}"
    fields:
      - { label: draft, name: Draft, widget: boolean, default: true }
      - { name: title, label: Title, widget: string }
      - { name: address, label: Address, widget: markdown }