backend:
  name: github
  repo: giopunt/DAAM

media_folder: static/assets
public_folder: /assets

collections:
  - name: gallery
    label: Gallery
    folder: galleries
    create: true
    slug: "{{slug}}"
    fields:
      - { label: draft, name: Draft, widget: boolean, default: true }
      - { name: name, label: Name, widget: string }
      - { name: website, label: Website, widget: string, required: false }
      - { name: logo, label: Logo, widget: image, required: false }
      - { name: address, label: Address, widget: markdown }
      - { name: contacts, label: Contacts, widget: markdown }
      - { name: program, label: Programma, widget: markdown, required: false }
      - { name: bio, label: Bio, widget: markdown }
      - { name: pressRelease1, label: "Press Release 1", widget: file, required: false }
      - { name: pressRelease2, label: "Press Release 2", widget: file, required: false }
      - { name: pressRelease3, label: "Press Release 3", widget: file, required: false }
      - { name: pressRelease4, label: "Press Release 4", widget: file, required: false }
      - { name: pressRelease5, label: "Press Release 5", widget: file, required: false }
      - { name: path, label: Path }
      - { name: latitude, label: Latitude, widget: string, required: false }
      - { name: longitude, label: Longitude, widget: string, required: false }
      - { 
          name: slider,
          label: "Photo Slider 1",
          widget: image,
          required: false
        }
      - { 
          name: slider2,
          label: "Photo Slider 2",
          widget: image,
          required: false
        }
      - { 
          name: slider3,
          label: "Photo Slider 3",
          widget: image,
          required: false
        }
      - { 
          name: slider4,
          label: "Photo Slider 4",
          widget: image,
          required: false
        }
      - { 
          name: slider5,
          label: "Photo Slider 5",
          widget: image,
          required: false
        }

  - name: event
    label: Event
    folder: events
    create: true
    slug: "{{slug}}"
    fields:
      - { label: draft, name: Draft, widget: boolean, default: true }
      - { name: title, label: Title, widget: string }
      - { name: description, label: Descrizione, widget: markdown, required: false }
      - { name: gallery, label: Gallery, widget: string }
      - { name: location, label: Location, widget: string }
      - { name: date, label: Date, widget: datetime,  dateFormat: "DD.MM.YYYY", timeFormat: "HH:mm" }
      - { name: endDate, label: "End Date", widget: datetime,  dateFormat: "DD.MM.YYYY", timeFormat: "HH:mm", required: false }
