backend:
  name: github
  repo: giopunt/DAAM

media_folder: static/assets
public_folder: /assets

collections:
  - name: gallery
    label: Gallery
    folder: galleries
    create: true
    slug: "{{slug}}"
    fields:
      - { label: draft, name: Draft, widget: boolean, default: true }
      - { name: name, label: Name, widget: string }
      - { name: website, label: Website, widget: string, required: false }
      - { name: logo, label: Logo, widget: image, required: false }
      - { name: address, label: Address, widget: markdown }
      - { name: contacts, label: Contacts, widget: markdown }
      - { name: program, label: Programma, widget: markdown, required: false }
      - { name: bio, label: Bio, widget: markdown }
      - { 
          name: slider,
          label: "Photo Slider",
          widget: image,
          required: false,
          allow_multiple: true
        }
      - { name: path, label: Path }
      - { name: latitude, label: Latitude, widget: string, required: false }
      - { name: longitude, label: Longitude, widget: string, required: false }

  - name: event
    label: Event
    folder: events
    create: true
    slug: "{{slug}}"
    fields:
      - { label: draft, name: Draft, widget: boolean, default: true }
      - { name: title, label: Title, widget: string }
      - { name: address, label: Address, widget: markdown }